
CREATE TABLE Users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR UNIQUE,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR NOT NULL,
    password VARCHAR NOT NULL
);


CREATE TABLE Groups (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE,
    description VARCHAR,
    password VARCHAR NOT NULL,
    owner INT REFERENCES Users(id)
);

